"""add verification fields

Revision ID: bb9cc80b8633
Revises: 9b3f5c7d2a6e
Create Date: 2026-07-02 15:31:47.883557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9cc80b8633'
down_revision: Union[str, Sequence[str], None] = '9b3f5c7d2a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires_at')
    op.drop_column('users', 'verification_code_expires_at')
    op.drop_column('users', 'reset_code')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    # ### end Alembic commands ###
